### ISSUE TITLE
Performance of layers

### ISSUE THREAD

**Issue by Nohus** [p-lr/MapCompose#44]
Multiple layers are less performant. This is quite significant in my case where I have 8 layers shown and zoomed out to see many tiles, every tile becomes 8 tiles to draw. This makes sense, but I think there is room for optimization: instead of drawing each tile separately every time, tiles from layers could be drawn into a composite tile "virtual layer", and then the actual map would only draw the composite tiles. This would make it so that instead of drawing 8 tiles per tile coordinate every frame, we would draw 9 tiles on the first frame (8 for composite tile, then composite tile on the screen), and then just 1 on following frames, by drawing just the cached composite tiles.

All layers logic could be moved to a single place and produce a single composite TileStreamProvider, that in the background uses all the TileStreamProviders from all layers to produce composite tiles (with caching). The rest of the library could work as if there was only 1 layer.

I think the speed up would be significant. What do you think about this idea?

**Comment by p-lr** [comment]
8 Layers means the screen is overdrawn 8 times, and it's normal that an Android device struggles in this situation. A more reasonable usage would be 2-3 layers.
Caching would cost significant more memory to be used, and would hinder the performance (despite the fact that there's no more overdraw). Also, the cache would have to be invalidated at each alpha change. 

You're describing what I've done in my app (remember when you first asked for layers). I assumed that the alpha wouldn't have to change, so I fused all layers beforehand, and supplied only one layer to the library.
But let's imagine that the alpha can be changed. Then caching tiles for the combination of layers and alpha can be part of a server process. MapCompose can display all layers while the server is baking tiles. When the application knows the server is ready, only one layer can be used (until the user plays with alpha). That way, all the heaving lifting is done server side and the performance is optimal.

**Comment by p-lr** [comment]
Not related to the performance of layers, when zoomed out, a lot of subsampled tiles are drawn. And this causes a noticeable slow down, even with one layer on some devices.
Something could be done, when the library knows that it wants to draw the entire map at a given level. Instead of requesting a zillion of a tiles, the application could supply a single pre-baked image. Especially with several layers, the speed up would be significant (when zooming out).

**Comment by Nohus** [comment]
> 8 Layers means the screen is overdrawn 8 times, and it's normal that an Android device struggles in this situation.

I agree, I'm not saying this is unexpected. Just that it could be fixed.

> Caching would cost significant more memory to be used

Would it? The cache would only contain tiles in the visible area. Surely more memory than no caching, but I would be surprised if it would decrease performance.

> the cache would have to be invalidated at each alpha change

At least in my app, the alpha only changes when the user toggles a setting, which is a one time event, not an animation. I don't see this as an issue.

> Then caching tiles for the combination of layers and alpha can be part of a server process

Haha, it was, I was serving tiles for all combinations of layers the app could display. I asked for and then used the layers feature so that's not necessary. This is less code on the server, less storage on the server, less code in the app to request all the different tile types, better layer switching experience (when the user turns on a layer, only elements of that layer load in, instead of the entire screen having to reload / same for turning off a layer, only relevant elements disappear). And importantly this is less storage used by the http cache in the app, because instead of caching a tile for every combination of layers, there is just 1 tile per layer (per coordinate).

> That way, all the heaving lifting is done server side and the performance is optimal.

That's true in terms of processing, but it's also more network bandwith for the app, more cache storage in the app, and worse user experience due to the entire map having to reload every time a layer is toggled. I was really happy with how the feel of my app improved when I switched to layers.

**Comment by p-lr** [comment]
As I'm not 100% sure, I'm asking more precisely. Is the performance not good enough when zoomed out, or stutters happen even at scale 1?
Depending on your answer, I'll elaborate.

**Comment by Nohus** [comment]
At scale 1 you can see ~80% of my map, so it's equivalent to "zoomed out", and the stutters happen there. When zoomed in close so that less tiles are visible the performance is fine.

**Comment by p-lr** [comment]
How many levels do you have?

**Comment by Nohus** [comment]
16, but you can see at most 8 at a time.

**Comment by p-lr** [comment]
Just for the record, scale 1 is the scale of the last level (the 16th). So I don't understand how 80% is visible at that level.

**Comment by Nohus** [comment]
Oh sorry, I thought you meant layers, my bad. I have only 1 level.

**Comment by p-lr** [comment]
Alright, that makes sense now.

**Comment by p-lr** [comment]
I'll elaborate later tonight or tomorrow.

**Comment by p-lr** [comment]
About caching composite tiles, I don't think this is a viable solution because:
- Although it would improve specific situations when the user scrolls back and forth (returning to an area where tiles are already cached), it would not be applicable for other use cases such as multiple scroll, not returning to already seen areas.
- It would make things much more complicated to deal with alpha change. Invalidating the cache, reprocess the visible area...
- That's more computations to perform at runtime, and more memory allocations (composite bitmaps creation) and computations when there are stutters already. That would make things worse, just to improve some specific use case.

Clearly caching is a no go for me. But that doesn't mean there's no solution to your problem.
In fact, I've thought of a possible solution. You have only one level, and I remember that you mentioned in another issue that your max scale is 4 (or maybe even more). Consequently, you're up-scaling tiles and you're fine with that.
Using the magnifying factor, you can alter from which level tiles are requested. When you have only one level, the magnifying factor has no effect. However, if you add one level which is a sub-sampling of your original level (in other words, you need 4 tiles from the original level to make 1 tile of the sub-sampled level), then a magnifying factor of 1 makes sense. 
At scale 1, instead of loading tiles from the original level, tiles from the sub-sampled level will be used (and they all cover 4 times bigger area, far less memory allocations, ...).
So that's what I would try. One more sub-sampled level (for each layers), and magnifying factor of 1.

**Comment by Nohus** [comment]
> Although it would improve specific situations when the user scrolls back and forth

> That would make things worse, just to improve some specific use case.

With a tile size of 256, if you scroll to the right, you are drawing the exact same tiles 256 map draws in a row. I don't think it's fair to call it a specific situation. This is the overwhelming majority of cases: map moved 1 pixel (due to user gesture or animation), no tile changes, need to redraw all the tiles that are already drawn shifted by 1 pixel. When considering a scroll by 1000 pixels, there were 1000 times we had to draw the map, but only 4 times new tiles were needed. That's 996 out of 1000 draws that could've been cached. Hardly a specific use case.

> It would make things much more complicated to deal with alpha change. Invalidating the cache, reprocess the visible area...

Sure, I'm not saying it's simple. But even a very naive approach of "invalidate the cache every time any tile is loaded" + "don't put tiles with alpha in the cache" would cover almost all draws, since almost all draws use tiles that are already on the screen.

> That's more computations to perform at runtime

It adds 1 additional upfront draw, the more layers you have the more sense it makes. With 8 layers I would take one frame with 9 draws for all other frames to be 1 draw, instead of all frames being 8 draws. I would take waiting 50ms longer for the first frame, for smooth scrolling, rather than 50ms faster first frame but sluggish scrolling.

> and more memory allocations

That's fair. I would make it a setting and an app could make use of it if it makes sense on the particular device.

> I remember that you mentioned in another issue that your max scale is 4 (or maybe even more)

My max scale is 16 and most usage happens at scales 2 and higher, yes!

> In fact, I've thought of a possible solution.

Sounds good, thank you, I will try that and see what happens.

**Comment by p-lr** [comment]
> When considering a scroll by 1000 pixels, there were 1000 times we had to draw the map, but only 4 times new tiles were needed. That's 996 out of 1000 draws that could've been cached. Hardly a specific use case.

You're assuming that drawing operations cause the stutters. Bit I doubt that. I believe memory allocations are the cause.
This can be measured of course, but at least that explains why my gut tells me no. Also yes, scrolling 4 tiles right and 4 tiles left, though common, is just one of many use cases. You have pilots who are recording themselves in their airplane (I'm not joking).

**Comment by p-lr** [comment]
To clarify my previous comment, memory usage has direct impact on performance. Even though there's a few memory allocations at given point in time, if the memory usage is high, performance is terrible. Memory is performance (99% of the time, unless something is really wrong).

**Comment by p-lr** [comment]
In addition to the solution I suggested, there's also one more thing you can try -- and it's pretty easy to do. 
Increase the depth of the tile pool. You'll find a class name `TilePool` or similar. The current is 300 if I remember well. That's appropriate for up to 3 levels. Since you have 8 levels... Try to see if increasing that number to 600 or maybe more (that's crazy 🤣) has an impact.

**Comment by p-lr** [comment]
I've investigated the issue on the demo app. 7 layers were largely enough to show some serious performance issue when scale is below 1 (mostly). As expected, it's directly related to the number of tiles to render. When the number reaches a certain limit, the rendering pipeline cannot keep up.

I'm not comfortable with the current situation. The layers feature is nice, as it allows for dynamic alpha changing of a layer (as one would expect from such a feature). However, this has a cost. To be able to do that, the library must keep in memory the bitmaps of each individual layer. That strategy isn't scalable. The number of layers cannot grow without any limit.
To be scalable, a strategy should submit a bounded list of tiles to render. As each bitmap from each layer is retrieved, the related bitmap should be updated _in memory_, without allocating a new bitmap. The cost? No more dynamic alpha changing, as every time a bitmap is updated, the "history" is re-written. That strategy would be completely different from what is done now in the library. To be honest, as of now, I don't know how to do that technically.

**Comment by Nohus** [comment]
> The layers feature is nice, as it allows for dynamic alpha changing

I will just comment that I personally think the layers feature is nice without the dynamic alpha at all. It's a nice addition but to me it wasn't necessary, the layers themselves were. I'm using layers to stack different layers of information into a complete map, with the user being able turn them on or off. None of this uses the layer alpha feature.

**Comment by Nohus** [comment]
Actually, probably people using layers to display complete maps with alpha, need the alpha feature, but won't use more than 2-3 layers. People using layers to stack different layers if information on a single map (like me), probably don't need the alpha feature. If the layer alpha feature complicates things a lot when trying to increase performance, and performance would only be a concern for people using lots of layers and so probably don't need it, then maybe the layers alpha feature should be able to be turned off for better performance?

This probably doesn't make sense, just some thoughts.

**Comment by p-lr** [comment]
I'm also ready to sacrifice dynamic alpha change for better design and performance. That's a nice to have, but performance shouldn't be sacrificed. After all, having to re-render the screen on alpha change is acceptable, since it should be a one-time adjustment from the user.
So that's settled, I'll explore the implications of the layers feature revamp.

**Comment by p-lr** [comment]
The new `layers-revamp` should address the issues you've been having. Several important changes were made.

* The tile drawing strategy is radically different. Tiles from all layers are no longer kept in memory, just the
superposition is. 

* While previous versions didn't leverage `TileStreamProvider`'s suspend call, this new version greatly benefits from that. If you're using a library like Retrofit to perform remote http fetch (and suspend calls), tile loading will be optimal since all layers are  fetched concurrently. That was already the case before, but not thanks to suspending calls.

* Memory allocations have been dramatically reduced in some cases. Per my tests, I've seen great improvements in
[HWUI](https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering) profiling

**Comment by Nohus** [comment]
@p-lr Sorry for the late response, I was away from this during the holiday period.

I have tried the `layers-revamp` branch, and can confirm it removes all the performance problems I was seeing. Unfortunately it introduces a few other issues though:

- Zooming in or out sometimes triggers a redraw of the entire map (all tiles disappear and load again)
- Adding/removing layers sometimes triggers a redraw of the entire map (as opposed to just the layer's elements appearing/disappearing)
- Switching layers results in incorrect states during loading: I have layer A, I remove layer A and add layer B. The expected outcome is for layer A to disappear, then layer B to appear, with a period of loading in-between. Instead, layer B appears on top of layer A (which looks very wrong with both being visible at the same time), and after it finishes loading layer A disappears.

All of these don't exist on `v2`.

**Comment by p-lr** [comment]
> Sorry for the late response, I was away from this during the holiday period.

That what I thought, no worries.

I think that I reproduced all the issues you mentioned. However, just to clarify, when you say "triggers a redraw of the entire map", do you mean that the screen goes blank and previously visible tiles (which should still be visible when zooming in/out) disappear before new tiles are loaded?
If that's so, the good news is that I reproduced them, and I should be able to come up with a fix.

**Comment by Nohus** [comment]
Yes, that's what I mean, screen goes blank and tiles redraw from there.

**Comment by p-lr** [comment]
Per my tests, the issues you reported are fixed. However now, dynamically changing the layer opacity redraws the entire screen.
This is consistent with what I explained a few weeks ago, and my attempt to circumvent that "no so good effect" lead to potential out of memory issues. I believe this is acceptable, provided the user doesn't change the opacity too often (with just a few steps adjustments).

**Comment by Nohus** [comment]
Thank you, I will give it a go later today.

**Comment by Nohus** [comment]
I have tested it:

- The zooming redraws are fixed.
- Adding/removing a layer makes the entire map redraw/blink (previously it was happening sometimes, and it's always happening). I am guessing this is because now alpha is shared among all tiles and so the new layer loading in also adds the fade-in affect to the existing tiles? If I have a base layer and roads layer, and turn on the roads layer, previously just roads would fade in with most of the screen remaining unchanged. Now the entire map blinks. Same for turning off the roads layer.
- The layer switching issue is fixed. However the after switching, the old layer stays on screen (as new layer is loaded I presume), and then gets replaced with the new layer, with no blank state. I would expect the old layer to be gone immediately, see a blank screen, and then the new layer appear as it's loaded. This may seem irrelevant if you are only using the map, but I have other things on the screen that only make sense to be visible when the map shows particular layers. Now I switch layers, and the screen is in an inconsistent state, that makes sense for the new layer, even though the old layer is still on the map.

**Comment by p-lr** [comment]
I've edited your post to put numbers. 
Obviously, issue 2 is my mistake and I could fix it quickly. 
Haven't looked into 3 yet.

**Comment by p-lr** [comment]
Issue 2 should be fixed now. However, I couldn't reproduce issue 3. Let me know if you still have it.

**Comment by Nohus** [comment]
Issue 2 is indeed fixed! But issue 3 remains. When you remove layer A and add layer B, you can still see layer A on the screen for some time, as layer B is processing in the background. Then after the loading wait the layers are replaced correctly. The issue is that during the waiting period layer A should be gone already.

**Comment by p-lr** [comment]
I have found an anomaly that might explain what you describe. Is it fixed now?

**Comment by Nohus** [comment]
Doesn't seem to have made a difference.

**Comment by Nohus** [comment]
I can try to reproduce it in the test app if that would help?

**Comment by p-lr** [comment]
That would help indeed, thanks

**Comment by Nohus** [comment]
I am not sure if this is the same bug I am seeing in my app but there is definitely something wrong here. This is on branch `bug-reproduction`. Notice how when I click the button the red layer is still there (although at different level?! :thinking:) and later the new layer loads on top of it.

https://user-images.githubusercontent.com/11064768/148292321-3397ccfe-1da3-4153-9f53-58876a3da31b.mp4

**Comment by p-lr** [comment]
Alright I'll have a look at it tomorrow. I know that the changes I made to fix recent issues opened the possibility of new ones, but I have a plan.

**Comment by p-lr** [comment]
I have a working version, but I'm double checking there's no regressions.
The next version should behave as you expect for the particular case of replacing an existing layer.
However, if you have two layers A and B, and you replace B with C, the screen won't go blank. Tiles of A + C will load while tiles of A+B are still on screen.
I'll post my changes soon.

**Comment by Nohus** [comment]
> However, if you have two layers A and B, and you replace B with C, the screen won't go blank. Tiles of A + C will load while tiles of A+B are still on screen.

I would expect B to disappear immediately (so you only see A), and then A+C to load in. But it doesn't matter too much for me, it only does when I am replacing all layers, so that's enough for my use case. :+1:

**Comment by p-lr** [comment]
> I would expect B to disappear immediately (so you only see A), and then A+C to load in. But it doesn't matter too much for me, it only does when I am replacing all layers, so that's enough for my use case.

That would be logical, however impossible to do here because tiles are made of A + B (fused together).

**Comment by p-lr** [comment]
Changes are pushed on `layers-revamp`

**Comment by Nohus** [comment]
> I am not sure if this is the same bug I am seeing in my app

Turns out it wasn't :/

**Comment by Nohus** [comment]
I can confirm everything is fine now, when I don't use markers. But there is some performance issue with markers. Likely it's just a problem on my side though, not the library, I will look into it.

**Comment by Nohus** [comment]
This is all fixed now, thank you. I will open a separate issue regarding markers.
